name: ci

on:
  push:
    branches:
      - main
    paths:
      - "charts/**"

  workflow_dispatch:

jobs:
  publish:
    permissions:
      contents: read
      packages: write

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish helm chart
        run: |
          CHART_VERSION=$(yq -r .version ./charts/k8s-info/Chart.yaml)

          helm package ./charts/k8s-info --version $CHART_VERSION
          helm push ./k8s-info-${CHART_VERSION}.tgz \
            oci://ghcr.io/${{ github.repository }}/charts
